## Markov Chain 

#### markov 성질을 갖는다. 
다음 시점의 확률은 바로 직전 시점에 의해 영향받는다.

$$
P(X_n | X_1, X_2, X_3, ... X_{n-1}) \ \ = \ \ P(X_n | X_{n-1}) 
$$

#### Transition matrix 를 갖는다. 

#### 주로 이런 곳에 많이 쓰인다. 

In [15]:
import numpy as np
trMatrix = np.array([[0.6, 0.3, 0.1],[0.1, 0.5, 0.4],[0.5, 0.4, 0.1]])


def multiplyN(n, matrix):
    init = matrix
    for i in range(n):
        init = np.dot(init, matrix)
    return init    

after = multiplyN(5, trMatrix)
after


array([[0.377144, 0.402337, 0.220519],
       [0.376051, 0.402884, 0.221065],
       [0.376779, 0.402519, 0.220702]])

In [12]:
after10 = multiplyN(10, trMatrix)
after10

array([[0.37662464, 0.40259677, 0.22077859],
       [0.37662198, 0.4025981 , 0.22077992],
       [0.37662376, 0.40259721, 0.22077903]])

In [13]:
after300 = multiplyN(300, trMatrix)
after300

array([[0.37662338, 0.4025974 , 0.22077922],
       [0.37662338, 0.4025974 , 0.22077922],
       [0.37662338, 0.4025974 , 0.22077922]])

In [ ]:
sentences = "Thank you so much. That is so nice. he is a great guy. He does not get a fair press. he does not get it. It is just not fair. And I have to tell you I am here, and very strongly here, because I have great respect for Steve King and have great respect likewise for Citizens United, David and everybody, and tremendous resect for the Tea Party. Also, also the people of Iowa. They have something in common. Hard-working people"
print(sentences)

In [3]:
corpus = sentences.split()
print(corpus)

['Thank', 'you', 'so', 'much.', 'That', 'is', 'so', 'nice.', 'he', 'is', 'a', 'great', 'guy.', 'He', 'does', 'not', 'get', 'a', 'fair', 'press.', 'he', 'does', 'not', 'get', 'it.', 'It', 'is', 'just', 'not', 'fair.', 'And', 'I', 'have', 'to', 'tell', 'you', 'I', 'am', 'here,', 'and', 'very', 'strongly', 'here,', 'because', 'I', 'have', 'great', 'respect', 'for', 'Steve', 'King', 'and', 'have', 'great', 'respect', 'likewise', 'for', 'Citizens', 'United,', 'David', 'and', 'everybody,', 'and', 'tremendous', 'resect', 'for', 'the', 'Tea', 'Party.', 'Also,', 'also', 'the', 'people', 'of', 'Iowa.', 'They', 'have', 'something', 'in', 'common.', 'Hard-working', 'people']


In [4]:
def make_pairs(corpus):
    for i in range(len(corpus) - 1):
        yield (corpus[i], corpus[i + 1])

pairs = make_pairs(corpus)
pairs

<generator object make_pairs at 0x7efbf46d4bf8>

In [5]:
word_dict = {}
for word_1, word_2 in pairs:
    if word_1 in word_dict.keys():
        word_dict[word_1].append(word_2)
    else:
        word_dict[word_1] = [word_2]

word_dict        

{'Also,': ['also'],
 'And': ['I'],
 'Citizens': ['United,'],
 'David': ['and'],
 'Hard-working': ['people'],
 'He': ['does'],
 'I': ['have', 'am', 'have'],
 'Iowa.': ['They'],
 'It': ['is'],
 'King': ['and'],
 'Party.': ['Also,'],
 'Steve': ['King'],
 'Tea': ['Party.'],
 'Thank': ['you'],
 'That': ['is'],
 'They': ['have'],
 'United,': ['David'],
 'a': ['great', 'fair'],
 'also': ['the'],
 'am': ['here,'],
 'and': ['very', 'have', 'everybody,', 'tremendous'],
 'because': ['I'],
 'common.': ['Hard-working'],
 'does': ['not', 'not'],
 'everybody,': ['and'],
 'fair': ['press.'],
 'fair.': ['And'],
 'for': ['Steve', 'Citizens', 'the'],
 'get': ['a', 'it.'],
 'great': ['guy.', 'respect', 'respect'],
 'guy.': ['He'],
 'have': ['to', 'great', 'great', 'something'],
 'he': ['is', 'does'],
 'here,': ['and', 'because'],
 'in': ['common.'],
 'is': ['so', 'a', 'just'],
 'it.': ['It'],
 'just': ['not'],
 'likewise': ['for'],
 'much.': ['That'],
 'nice.': ['he'],
 'not': ['get', 'get', 'fair.'],
 'o

In [10]:
import numpy as np
start_word = np.random.choice(corpus)


chain = [start_word]
n_words = 20

print(chain)
for i in range(n_words):
    chain.append(np.random.choice(word_dict[chain[-1]]))
print(' '.join(chain))    

['have']
have to tell you so much. That is a fair press. he does not get a great guy. He does not
