In [2]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np 

In [121]:
data = load_iris()
X, y, column_names = data['data'], data['target'], data['feature_names']
X = pd.DataFrame(X, columns = column_names)
X['target'] = y

In [122]:
X['target']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [123]:
X['target'].values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [125]:
np.asarray(X)[:, 4]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [128]:

def bootstrap(df, nboot):
    idx = np.random.randint(df.shape[0], size = (nboot, df.shape[0]))
    idx_flat = np.ravel(idx)
    
    return df.iloc[idx_flat, :]

bootstappedDF = bootstrap(X, 100)
bootstapped_smallDF = bootstrap(X, 1)


In [114]:
bootstapped_smallDF

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
93                 5.0               2.3                3.3               1.0   
138                6.0               3.0                4.8               1.8   
94                 5.6               2.7                4.2               1.3   
88                 5.6               3.0                4.1               1.3   
112                6.8               3.0                5.5               2.1   
..                 ...               ...                ...               ...   
4                  5.0               3.6                1.4               0.2   
117                7.7               3.8                6.7               2.2   
21                 5.1               3.7                1.5               0.4   
107                7.3               2.9                6.3               1.8   
86                 6.7               3.1                4.7               1.5   

     target  
93        1  
138       2  
94        1  
88        1  
112       2  
..      ...  
4         0  
117       2  
21        0  
107       2  
86        1  

[150 rows x 5 columns]

In [131]:
X, y = bootstappedDF.drop(columns = 'target'), bootstappedDF['target']

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(X,y, random_state = 44)

In [132]:
y_train

84     1
85     1
67     1
121    2
37     0
      ..
135    2
97     1
100    2
147    2
57     1
Name: target, Length: 11250, dtype: int64

In [41]:
prac = [0.2, 0.8]
np.asarray(prac)**2

array([0.04, 0.64])

### 어차피 입력값이 numpy 형태라서 속도 차이는 없다. 
만약에 입력값의 형태가 dp dataframe 형태라면 차이가 존재함. 

In [78]:
def getImpurity_faster(target, class_list):
    # 기본적으로 np.where 을 하면 tuple 형태이다. ( array([idx1, idx2 ,,, ]), ) 
    
    probas = []
    for one_class in class_list:
        prob = np.where(target == one_class)[0].size / target.shape[0]
        probas.append(prob)
    
    # gini 계수를 구한다. 
    return 1-np.sum(np.asarray(probas)**2)
    

def getImpurity(y, class_list):
    probas = []
    for one_class in class_list:
        proba = y[y==one_class].shape[0] / y.shape[0]
        probas.append(proba)
        
    return 1-np.sum(np.asarray(probas)**2)   

In [79]:
%%time

only_y = bootstappedDF["target"]
target_name = "target"
class_list = [0,1,2]


getImpurity_faster(np.asarray(only_y), class_list)

CPU times: user 18.4 ms, sys: 0 ns, total: 18.4 ms
Wall time: 17.7 ms


0.6666666634746666

In [80]:
%%time
getImpurity(only_y, class_list)

CPU times: user 48.9 ms, sys: 0 ns, total: 48.9 ms
Wall time: 48.3 ms


0.6666666634746666

In [135]:
 
        
    
def calcBestSplit(X, y):
        '''
        Calculates the best possible split for the concrete node of the tree
        '''
        class_list = [0,1,2]
        bestSplitCol = None
        bestThresh = None
        bestInfoGain = -999
        
        # 나누기 전 현재의 데이터 분포에서 impurity 를 계산한다. 
        impurityBefore = getImpurity(y, class_list)
        
        # X는 2차원의 table 데이터 이므로, (행 수, 열 수) 의 shape을 갖는다. 
        # 따라서, 모든 variable 들에 대해서 info gain을 계산해야 하므로 loop 돌린다. 
        
        for col in range(X.shape[1]):
            x_col = X[:, col]  # 행은 전부다, 열은 col으로 지정한 열만. 
            
            # 각각의 모든 value 들을 기준로 나눈다. 
            for x_i in x_col:
                threshold = x_i
                y_right = y[x_col > threshold]
                y_left = y[x_col <= threshold]
                
                if y_right.shape[0] == 0 or y_left.shape[0] == 0:
                    continue
                    
                # calculate impurity for the right and left nodes
                impurityRight = getImpurity(y_right, class_list)
                impurityLeft = getImpurity(y_left, class_list)
                
                # calculate information gain
                infoGain = impurityBefore
                infoGain -= (impurityLeft * y_left.shape[0] / y.shape[0]) + (impurityRight * y_right.shape[0] / y.shape[0])
                
                # is this infoGain better then all other?
                if infoGain > bestInfoGain:
                    bestSplitCol = col
                    bestThresh = threshold
                    bestInfoGain = infoGain
                    
        
        # if we still didn't find the split
        if bestInfoGain == -999:
            return None, None, None, None, None, None
        
        # making the best split
        
        x_col = X[:, bestSplitCol]
        x_left, x_right = X[x_col <= bestThresh, :], X[x_col > bestThresh, :]
        y_left, y_right = y[x_col <= bestThresh], y[x_col > bestThresh]
        
        return bestSplitCol, bestThresh, x_left, y_left, x_right, y_right

In [137]:
%%time 

x = np.asarray(X_train)
splitCol, thresh, x_left, y_left, x_right, y_right = calcBestSplit(x, y_train)


CPU times: user 1min 42s, sys: 0 ns, total: 1min 42s
Wall time: 1min 42s


In [136]:
def calcBestSplit_faster(X, y):
        '''
        X : np.asarray 를 통해서 이미 numpy array 형태로 변환된 것이다. 
        Calculates the best possible split for the concrete node of the tree
        '''
        class_list = [0,1,2]
        bestSplitCol = None
        bestThresh = None
        bestInfoGain = -999
        
        # 나누기 전 현재의 데이터 분포에서 impurity 를 계산한다. 
        impurityBefore = getImpurity_faster(y, class_list)
        
        # X는 2차원의 table 데이터 이므로, (행 수, 열 수) 의 shape을 갖는다. 
        # 따라서, 모든 variable 들에 대해서 info gain을 계산해야 하므로 loop 돌린다. 
        
        for col in range(X.shape[1]):
            
            # X 가 이미 np.array 아래와같이 indexing이 가능. .iloc이 아님. 
            x_col = X[:, col]  # 행은 전부다, 열은 col으로 지정한 열만. 
            
            # 각각의 모든 value 들을 기준로 나눈다. 
            for x_i in x_col:
                threshold = x_i
                y_right = np.where(y  > threshold)[0]
                y_left = np.where(y <=threshold)[0]
                
                if y_right.shape[0] == 0 or y_left.shape[0] == 0:
                    continue
                    
                # calculate impurity for the right and left nodes
                impurityRight = getImpurity_faster(y_right, class_list)
                impurityLeft = getImpurity_faster(y_left, class_list)
                
                # calculate information gain
                infoGain = impurityBefore
                infoGain -= (impurityLeft * y_left.shape[0] / y.shape[0]) + (impurityRight * y_right.shape[0] / y.shape[0])
                
                # is this infoGain better then all other?
                if infoGain > bestInfoGain:
                    bestSplitCol = col
                    bestThresh = threshold
                    bestInfoGain = infoGain
                    
        
        # if we still didn't find the split
        if bestInfoGain == -999:
            return None, None, None, None, None, None
        
        # making the best split
        
        x_col = X[:, bestSplitCol]
        x_left, x_right = X[x_col <= bestThresh, :], X[x_col > bestThresh, :]
        y_left, y_right = y[x_col <= bestThresh], y[x_col > bestThresh]
        
        return bestSplitCol, bestThresh, x_left, y_left, x_right, y_right

In [138]:
%%time 

x = np.asarray(X_train)
splitCol, thresh, x_left, y_left, x_right, y_right = calcBestSplit_faster(x, y_train)


CPU times: user 9.59 s, sys: 0 ns, total: 9.59 s
Wall time: 9.59 s
